=== ANR-ArTerm/index_oeuvres/schema/artwork.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "http://example.com/artwork.schema.json",
  "title": "Artwork Entry",
  "type": "object",
  "required": [
    "id",
    "entry_type",
    "title"
  ],
  "properties": {
    "id": {
      "type": "string"
    },
    "QID_wikidata": {
      "type": "string"
    },
    "entry_type": {
      "type": "string",
      "enum": ["artwork"]
    },
    "title": {
      "type": "string"
    },
    "creator": {
      "type": "array",
      "items": {
        "type": "object",
        "required": ["xml_id", "role"],
        "properties": {
          "xml_id": {
            "type": "string"
          },
          "role": {
            "type": "string"
          }
        },
        "additionalProperties": false
      }
    },
    "dateCreated": {
      "type": "object",
      "properties": {
        "startYear": {
          "type": ["integer", "null"],
          "minimum": -9999,
          "maximum": 9999
        },
        "endYear": {
          "type": ["integer", "null"],
          "minimum": -9999,
          "maximum": 9999
        },
        "text": {
          "type": "string"
        }
      },
      "additionalProperties": false
    },
    "materialsAndTechniques": {
      "type": "string"
    },
    "location": {
        "oneOf": [
            {
            "type": "object",
            "required": ["type", "institution"],
            "properties": {
                "type": {
                "type": "string",
                "enum": ["holding_institution"]
                },
                "institution": {
                "type": "object",
                "required": ["name"],
                "properties": {
                    "name": { "type": "string" },
                    "place": { "type": "string" },
                    "inventory_number": { "type": "string" },
                    "url": { "type": "string", "format": "uri" }
                },
                "additionalProperties": false
                }
            },
            "additionalProperties": false
            },
            {
            "type": "object",
            "required": ["type", "place"],
            "properties": {
                "type": {
                "type": "string",
                "enum": ["place"]
                },
                "place": {
                "type": "object",
                "properties": {
                    "city": { "type": "string" },
                    "country": { "type": "string" },
                    "coordinates": {
                    "type": "object",
                    "properties": {
                        "latitude": { "type": "number" },
                        "longitude": { "type": "number" }
                    },
                    "required": ["latitude", "longitude"],
                    "additionalProperties": false
                    }
                },
                "additionalProperties": false
                }
            },
            "additionalProperties": false
            },
            {
            "type": "object",
            "required": ["type"],
            "properties": {
                "type": {
                "type": "string",
                "enum": ["unlocated", "multiple_locations"]
                }
            },
            "additionalProperties": false
            }
        ]
    },
    "related_works": {
      "type": "array",
      "items": {
        "type": "object",
        "required": ["link_type", "xml_id_work"],
        "properties": {
          "link_type": {
            "type": "string"
          },
          "xml_id_work": {
            "type": "string"
          }
        },
        "additionalProperties": false
      }
    },
    "contained_by_ensemble": {
      "type": "object",
      "properties": {
        "link_type": {
          "type": "string"
        },
        "xml_id_work": {
          "type": "string"
        }
      },
      "additionalProperties": false
    },
    "bibliography": {
      "type": "array",
      "items": {
        "type": "object",
        "required": ["zotero_key"],
        "properties": {
          "zotero_key": {
            "type": "string"
          },
          "location": {
            "type": "string"
          }
        },
        "additionalProperties": false
      }
    },
    "illustrations": {
      "type": "array",
      "items": {
        "type": "object",
        "required": ["id", "url"],
        "properties": {
          "id": {
            "type": "integer"
          },
          "url": {
            "type": "string",
            "format": "uri"
          },
          "copyright": {
            "type": "string"
          },
          "caption": {
            "type": "string"
          },
          "storage": {
            "type": "string"
          }
        },
        "additionalProperties": false
      }
    },
    "description": {
      "type": "string"
    },
    "commentary": {
      "type": "string"
    },
    "history": {
      "type": "array",
      "items": {
        "type": "object",
        "required": ["date", "type", "author"],
        "properties": {
          "date": {
            "type": "string",
            "format": "date-time"
          },
          "type": {
            "type": "string",
            "enum": ["created", "modified"]
          },
          "author": {
            "type": "string"
          }
        },
        "additionalProperties": false
      },
      "minItems": 1
    },
    "complete_entry": {
      "type":"boolean"
    }
  },
  "additionalProperties": false
}

=== ANR-ArTerm/index_oeuvres/data/entry_artwork/GBScultoriViergeCroissant.json
{
  "id": "GBScultoriViergeCroissant",
  "QID_wikidata": "",
  "title": "",
  "creator": [
    {
      "xml_id": "GiovanniBattistaScultori",
      "role": "graveur"
    }
  ],
  "entry_type": "artwork",
  "materialsAndTechniques": "",
  "dateCreated": {
    "startYear": null,
    "endYear": null,
    "text": ""
  },
  "location": {
    "type": "multiple_locations"
  },
  "related_works": [],
  "bibliography": [
    {
      "zotero_key": "straussIllustratedBartsch311986",
      "location": "n° 4 (378)"
    }
  ],
  "illustrations": [],
  "description": "",
  "commentary": "",
  "history": [
    {
      "date": "2026-03-06T14:48:18.473860",
      "type": "created",
      "author": "Pierre"
    }
  ],
  "complete_entry": false
}

=== ANR-ArTerm/index_oeuvres/data/entry_artwork/PoussinMoiseLeNotre.json
{
  "id": "PoussinMoiseLeNotre",
  "QID_wikidata": "",
  "entry_type": "artwork",
  "title": "Moïse sauvé des eaux",
  "creator": [
    {
      "xml_id": "NicolasPoussin",
      "role": "peintre"
    }
  ],
  "dateCreated": {
    "startYear": 1638,
    "endYear": 1638,
    "text": "1638"
  },
  "location": {
    "type": "holding_institution",
    "institution": {
      "name": "Musée du Louvre",
      "place": "Paris",
      "inventory_number": "INV 7271",
      "url": "https://collections.louvre.fr/ark:/53355/cl010066620"
    }
  },
  "related_works": [],
  "bibliography": [],
  "illustrations": [
    {
      "id": 0,
      "url": "https://upload.wikimedia.org/wikipedia/commons/9/93/Poussin_finding_of_moses_1638.jpg",
      "storage": "online",
      "copyright": "Domaine public, photo Shonagon 2024-02-15",
      "caption": ""
    }
  ],
  "description": "Cette version du Moïse a appartenu au célèbre jardinier André Le Nôtre ; on l'a nommée ainsi pour la distinguer d'une version identique également conservée au musée du Louvre.",
  "commentary": "",
  "history": [
    {
      "date": "2026-01-28T22:31:29.801398",
      "type": "created",
      "author": "Carla"
    }
  ],
  "materialsAndTechniques": "huile sur toile",
  "complete_entry": false
}

=== ANR-ArTerm/index_oeuvres/data/entry_artwork/FrancoAdorationDesRois.json
{
  "id": "FrancoAdorationDesRois",
  "QID_wikidata": "",
  "entry_type": "artwork",
  "title": "Adorations des rois mages",
  "creator": [
    {
      "xml_id": "BattistaFranco",
      "role": "graveur (attribué à)"
    }
  ],
  "dateCreated": {
    "startYear": 1530,
    "endYear": 1560,
    "text": "Milieu du XVIe siècle."
  },
  "location": {
    "type": "multiple_locations"
  },
  "related_works": [],
  "bibliography": [
    {
      "zotero_key": "straussIllustratedBartsch321979",
      "location": "n° 2 (154)"
    }
  ],
  "illustrations": [
    {
      "id": 0,
      "url": "https://media.britishmuseum.org/media/Repository/Documents/2014_10/1_12/4b0a855f_6a62_432a_93a4_a3b700c8c055/mid_00058862_001.jpg",
      "storage": "online",
      "copyright": "© The Trustees of the British Museum (CC BY-NC-SA 4.0)",
      "caption": "Londres, British Museum, inv. W,9.31 (https://www.britishmuseum.org/collection/object/P_W-9-31)"
    }
  ],
  "description": "",
  "commentary": "",
  "history": [
    {
      "date": "2026-03-18T17:53:05.357074",
      "type": "created",
      "author": "Pierre"
    },
    {
      "date": "2026-03-18T18:04:41.870590",
      "type": "modified",
      "author": "Pierre"
    }
  ],
  "materialsAndTechniques": "eau-forte et burin",
  "contained_by_ensemble": {},
  "complete_entry": false
}

=== ANR-ArTerm/index_oeuvres/data/entry_artwork/DapRaphaelSibylleEnfant.json
{
  "id": "DapRaphaelSibylleEnfant",
  "QID_wikidata": "",
  "entry_type": "artwork",
  "title": "Sibylle lisant avec un enfant tenant une torche",
  "creator": [
    {
      "xml_id": "Raphael",
      "role": "auteur du modèle"
    }
  ],
  "dateCreated": {
    "startYear": 1520,
    "endYear": 1550,
    "text": "Vers 1520-1550"
  },
  "location": {
    "type": "multiple_locations"
  },
  "related_works": [],
  "bibliography": [],
  "illustrations": [
    {
      "id": 0,
      "url": "https://iiif.nypl.org/iiif/3/ps_prn_cd18_271/full/max/0/default.jpg",
      "storage": "online",
      "copyright": "New York, Public Library (https://digitalcollections.nypl.org/items/c196d6a0-9e3c-0136-0e05-2bb550afefad)",
      "caption": ""
    }
  ],
  "description": "",
  "commentary": "",
  "history": [
    {
      "date": "2026-04-24T17:42:34.718035",
      "type": "created",
      "author": "Pierre"
    }
  ],
  "materialsAndTechniques": "burin",
  "contained_by_ensemble": {},
  "complete_entry": false
}

=== ANR-ArTerm/index_oeuvres/data/entry_artwork/RaphaelLorenzoMedici.json
{
  "id": "RaphaelLorenzoMedici",
  "QID_wikidata": "https://www.wikidata.org/wiki/Q3399434",
  "entry_type": "artwork",
  "title": "Portrait de Lorenzo de' Medici",
  "creator": [
    {
      "xml_id": "Raphael",
      "role": "peintre"
    }
  ],
  "dateCreated": {
    "startYear": null,
    "endYear": null,
    "text": ""
  },
  "materialsAndTechniques": "",
  "location": {
    "type": "holding_institution",
    "institution": {
      "name": "",
      "place": "",
      "inventory_number": "",
      "url": ""
    }
  },
  "related_works": [],
  "bibliography": [
    {
      "zotero_key": "meyerzurcapellenRaphaelCriticalCatalogue2008",
      "location": "n° 80"
    }
  ],
  "illustrations": [],
  "description": "",
  "commentary": "",
  "history": [
    {
      "date": "2026-01-15T16:40:40.291788",
      "type": "created",
      "author": "Pierre"
    }
  ],
  "complete_entry": false
}

=== ANR-ArTerm/index_oeuvres/data/entry_artwork/RaimondiNeptune.json
{
  "id": "RaimondiNeptune",
  "QID_wikidata": "",
  "title": "Neptune",
  "creator": [
    {
      "xml_id": "MarcantonioRaimondi",
      "role": "graveur"
    }
  ],
  "entry_type": "artwork",
  "materialsAndTechniques": "burin",
  "dateCreated": {
    "startYear": null,
    "endYear": null,
    "text": ""
  },
  "location": {
    "type": "multiple_locations"
  },
  "related_works": [],
  "bibliography": [
    {
      "zotero_key": "straussIllustratedBartsch271978",
      "location": "n° 352 (264)"
    }
  ],
  "illustrations": [],
  "description": "",
  "commentary": "",
  "history": [
    {
      "date": "2026-03-06T14:48:18.466200",
      "type": "created",
      "author": "Pierre"
    }
  ],
  "complete_entry": false
}

=== ANR-ArTerm/index_oeuvres/data/entry_artwork/RaphaelDepositionBorghese.json
{
  "id": "RaphaelDepositionBorghese",
  "QID_wikidata": "https://www.wikidata.org/wiki/Q2500226",
  "entry_type": "artwork",
  "title": "Déposition Borghèse",
  "creator": [
    {
      "xml_id": "Raphael",
      "role": "peintre"
    }
  ],
  "dateCreated": {
    "startYear": null,
    "endYear": null,
    "text": ""
  },
  "materialsAndTechniques": "",
  "location": {
    "type": "holding_institution",
    "institution": {
      "name": "",
      "place": "",
      "inventory_number": "",
      "url": ""
    }
  },
  "related_works": [],
  "bibliography": [
    {
      "zotero_key": "meyerzurcapellenRaphaelCriticalCatalogue2001",
      "location": "n° 31"
    }
  ],
  "illustrations": [],
  "description": "",
  "commentary": "Problème p16 un carton disparu",
  "history": [
    {
      "date": "2026-01-15T16:40:40.206983",
      "type": "created",
      "author": "Pierre"
    }
  ],
  "complete_entry": false
}

=== ANR-ArTerm/index_oeuvres/data/entry_artwork/ApelleCalomnie.json
{
  "id": "ApelleCalomnie",
  "QID_wikidata": "https://www.wikidata.org/wiki/Q3207003",
  "entry_type": "artwork",
  "title": "Calomnie",
  "creator": [
    {
      "xml_id": "Apelle",
      "role": "peintre"
    }
  ],
  "dateCreated": {
    "startYear": null,
    "endYear": null,
    "text": ""
  },
  "materialsAndTechniques": "œuvre imaginaire ou disparue",
  "location": {
    "type": "holding_institution",
    "institution": {
      "name": "",
      "place": "",
      "inventory_number": "",
      "url": ""
    }
  },
  "related_works": [],
  "bibliography": [],
  "illustrations": [],
  "description": "",
  "commentary": "Peinture d'Apelle connue uniquement par une description de Lucien de Samosate",
  "history": [
    {
      "date": "2026-01-15T12:21:39.296040",
      "type": "created",
      "author": "Pierre"
    }
  ],
  "complete_entry": false
}
