=== ANR-ArTerm/index_oeuvres/schema/artwork.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "http://example.com/artwork.schema.json",
  "title": "Artwork Entry",
  "type": "object",
  "required": [
    "id",
    "entry_type",
    "title"
  ],
  "properties": {
    "id": {
      "type": "string"
    },
    "QID_wikidata": {
      "type": "string"
    },
    "entry_type": {
      "type": "string",
      "enum": ["artwork"]
    },
    "title": {
      "type": "string"
    },
    "creator": {
      "type": "array",
      "items": {
        "type": "object",
        "required": ["xml_id", "role"],
        "properties": {
          "xml_id": {
            "type": "string"
          },
          "role": {
            "type": "string"
          }
        },
        "additionalProperties": false
      }
    },
    "dateCreated": {
      "type": "object",
      "properties": {
        "startYear": {
          "type": ["integer", "null"],
          "minimum": -9999,
          "maximum": 9999
        },
        "endYear": {
          "type": ["integer", "null"],
          "minimum": -9999,
          "maximum": 9999
        },
        "text": {
          "type": "string"
        }
      },
      "additionalProperties": false
    },
    "materialsAndTechniques": {
      "type": "string"
    },
    "location": {
        "oneOf": [
            {
            "type": "object",
            "required": ["type", "institution"],
            "properties": {
                "type": {
                "type": "string",
                "enum": ["holding_institution"]
                },
                "institution": {
                "type": "object",
                "required": ["name"],
                "properties": {
                    "name": { "type": "string" },
                    "place": { "type": "string" },
                    "inventory_number": { "type": "string" },
                    "url": { "type": "string", "format": "uri" }
                },
                "additionalProperties": false
                }
            },
            "additionalProperties": false
            },
            {
            "type": "object",
            "required": ["type", "place"],
            "properties": {
                "type": {
                "type": "string",
                "enum": ["place"]
                },
                "place": {
                "type": "object",
                "properties": {
                    "city": { "type": "string" },
                    "country": { "type": "string" },
                    "coordinates": {
                    "type": "object",
                    "properties": {
                        "latitude": { "type": "number" },
                        "longitude": { "type": "number" }
                    },
                    "required": ["latitude", "longitude"],
                    "additionalProperties": false
                    }
                },
                "additionalProperties": false
                }
            },
            "additionalProperties": false
            },
            {
            "type": "object",
            "required": ["type"],
            "properties": {
                "type": {
                "type": "string",
                "enum": ["unlocated", "multiple_locations"]
                }
            },
            "additionalProperties": false
            }
        ]
    },
    "related_works": {
      "type": "array",
      "items": {
        "type": "object",
        "required": ["link_type", "xml_id_work"],
        "properties": {
          "link_type": {
            "type": "string"
          },
          "xml_id_work": {
            "type": "string"
          }
        },
        "additionalProperties": false
      }
    },
    "contained_by_ensemble": {
      "type": "object",
      "properties": {
        "link_type": {
          "type": "string"
        },
        "xml_id_work": {
          "type": "string"
        }
      },
      "additionalProperties": false
    },
    "bibliography": {
      "type": "array",
      "items": {
        "type": "object",
        "required": ["zotero_key"],
        "properties": {
          "zotero_key": {
            "type": "string"
          },
          "location": {
            "type": "string"
          }
        },
        "additionalProperties": false
      }
    },
    "illustrations": {
      "type": "array",
      "items": {
        "type": "object",
        "required": ["id", "url"],
        "properties": {
          "id": {
            "type": "integer"
          },
          "url": {
            "type": "string",
            "format": "uri"
          },
          "copyright": {
            "type": "string"
          },
          "caption": {
            "type": "string"
          },
          "storage": {
            "type": "string"
          }
        },
        "additionalProperties": false
      }
    },
    "description": {
      "type": "string"
    },
    "commentary": {
      "type": "string"
    },
    "history": {
      "type": "array",
      "items": {
        "type": "object",
        "required": ["date", "type", "author"],
        "properties": {
          "date": {
            "type": "string",
            "format": "date-time"
          },
          "type": {
            "type": "string",
            "enum": ["created", "modified"]
          },
          "author": {
            "type": "string"
          }
        },
        "additionalProperties": false
      },
      "minItems": 1
    },
    "complete_entry": {
      "type":"boolean"
    }
  },
  "additionalProperties": false
}

=== ANR-ArTerm/index_oeuvres/data/entry_artwork/RaphaelGracesFarnesina.json
{
  "id": "RaphaelGracesFarnesina",
  "QID_wikidata": "",
  "entry_type": "artwork",
  "title": "Cupidon et les grâces",
  "creator": [
    {
      "xml_id": "Raphael",
      "role": "peintre"
    },
    {
      "xml_id": "GiulioRomano",
      "role": "peintre"
    }
  ],
  "dateCreated": {
    "startYear": 1518,
    "endYear": 1518,
    "text": "1518"
  },
  "location": {
    "type": "holding_institution",
    "institution": {
      "name": "Villa Farnesina",
      "place": "Rome",
      "inventory_number": "",
      "url": ""
    }
  },
  "related_works": [
    {
      "link_type": "fait partie de",
      "xml_id_work": "LoggiaPsyche"
    }
  ],
  "bibliography": [],
  "illustrations": [
    {
      "id": 0,
      "url": "https://upload.wikimedia.org/wikipedia/commons/4/4f/Raffael%2C_Loggia_di_Psiche%2C_Villa_Farnesina%2C_Rome_09.jpg",
      "storage": "online",
      "copyright": "Public Domain, Web Gallery of Art : https://www.wga.hu/index_artists.html, ",
      "caption": ""
    }
  ],
  "description": "",
  "commentary": "",
  "history": [
    {
      "date": "2026-01-27T17:19:04.614668",
      "type": "created",
      "author": "Carla"
    },
    {
      "date": "2026-02-04T16:10:24.415181",
      "type": "modified",
      "author": "Pierre"
    }
  ],
  "materialsAndTechniques": "fresque",
  "contained_by_ensemble": {},
  "complete_entry": false
}

=== ANR-ArTerm/index_oeuvres/data/entry_artwork/TitienMartyreSaintLaurentVenise.json
{
  "id": "TitienMartyreSaintLaurentVenise",
  "QID_wikidata": "https://www.wikidata.org/wiki/Q7750471",
  "entry_type": "artwork",
  "title": "Le Martyre de saint Laurent",
  "creator": [
    {
      "xml_id": "Titien",
      "role": "peintre"
    }
  ],
  "dateCreated": {
    "startYear": 1558,
    "endYear": 1558,
    "text": "1558"
  },
  "location": {
    "type": "holding_institution",
    "institution": {
      "name": "Église Santa Maria Assunta",
      "place": "Venise",
      "inventory_number": "",
      "url": ""
    }
  },
  "related_works": [],
  "bibliography": [],
  "illustrations": [
    {
      "id": 0,
      "url": "https://upload.wikimedia.org/wikipedia/commons/a/ab/Interior_of_Chiesa_dei_Gesuiti_%28Venice%29_-_left_nave_-_The_Martyrdom_of_St_Lawrence_-_Titian.jpg",
      "storage": "online",
      "copyright": "Wikimedia Commons, Domaine Public, Archaeodontosaurus, https://commons.wikimedia.org/wiki/File:Interior_of_Chiesa_dei_Gesuiti_(Venice)_-_left_nave_-_The_Martyrdom_of_St_Lawrence_-_Titian.jpg",
      "caption": ""
    }
  ],
  "description": "",
  "commentary": "",
  "history": [
    {
      "date": "2026-04-27T15:55:36.867456",
      "type": "created",
      "author": "Carla"
    }
  ],
  "materialsAndTechniques": "huile sur toile",
  "contained_by_ensemble": {},
  "complete_entry": false
}

=== ANR-ArTerm/index_oeuvres/data/entry_artwork/PraxiteleAphroditeCnide.json
{
  "id": "PraxiteleAphroditeCnide",
  "QID_wikidata": "https://www.wikidata.org/wiki/Q618535",
  "entry_type": "artwork",
  "title": "Aphrodite de Cnide",
  "creator": [
    {
      "xml_id": "Praxitele",
      "role": "sculpteur"
    }
  ],
  "dateCreated": {
    "startYear": -400,
    "endYear": -326,
    "text": "IVe siècle avant notre ère"
  },
  "location": {
    "type": "unlocated"
  },
  "related_works": [],
  "bibliography": [],
  "illustrations": [
    {
      "id": 0,
      "url": "https://upload.wikimedia.org/wikipedia/commons/9/9a/Cnidus_Aphrodite_Altemps_Inv8619.jpg?utm_source=commons.wikimedia.org&utm_campaign=index&utm_content=original",
      "storage": "online",
      "copyright": "Wikimedia Commons (https://commons.wikimedia.org/wiki/File:Cnidus_Aphrodite_Altemps_Inv8619.jpg)",
      "caption": "Aphrodite de Cnide. Marbre, copie romaine d'après un original grec de Praxitèle du IVe siècle av. J.-C, Rome, palais Altemps, inv. 8619."
    }
  ],
  "description": "",
  "commentary": "",
  "history": [
    {
      "date": "2026-05-18T11:28:26.172592",
      "type": "created",
      "author": "Pierre"
    },
    {
      "date": "2026-05-18T11:30:00.939810",
      "type": "modified",
      "author": "Pierre"
    }
  ],
  "complete_entry": true,
  "materialsAndTechniques": "sculpture",
  "contained_by_ensemble": {}
}

=== ANR-ArTerm/index_oeuvres/data/entry_artwork/DaCarpiDiogene.json
{
  "id": "DaCarpiDiogene",
  "QID_wikidata": "",
  "title": "Diogène",
  "creator": [
    {
      "xml_id": "UgoDaCarpi",
      "role": "graveur"
    },
    {
      "xml_id": "Parmigianino",
      "role": "auteur du modèle"
    }
  ],
  "entry_type": "artwork",
  "materialsAndTechniques": "gravure sur bois en clair-obscur",
  "dateCreated": {
    "startYear": 1527,
    "endYear": 1530,
    "text": "vers 1527-1530"
  },
  "location": {
    "type": "multiple_locations"
  },
  "related_works": [],
  "bibliography": [
    {
      "zotero_key": "straussIllustratedBartsch481983",
      "location": "n° 10 (100)"
    }
  ],
  "illustrations": [
    {
      "id": 0,
      "url": "https://upload.wikimedia.org/wikipedia/commons/e/e0/Ugo_Carpi_d%27apr%C3%A8s_Le_Parmesan_Diog%C3%A8ne%2C_vers_1526.jpg",
      "copyright": "Wikimedia Commons (https://fr.wikipedia.org/wiki/Fichier:Ugo_Carpi_d%27apr%C3%A8s_Le_Parmesan_Diog%C3%A8ne,_vers_1526.jpg)",
      "caption": "Strasbourg, Cabinet des Estampes et des Dessins",
      "storage": "online"
    }
  ],
  "description": "",
  "commentary": "",
  "history": [
    {
      "date": "2026-03-06T14:48:18.472464",
      "type": "created",
      "author": "Pierre"
    },
    {
      "date": "2026-05-12T11:34:00.331010",
      "type": "modified",
      "author": "Pierre"
    }
  ],
  "contained_by_ensemble": {},
  "complete_entry": false
}

=== ANR-ArTerm/index_oeuvres/data/entry_artwork/VerrocchioBartolomeoColleoni.json
{
  "id": "VerrocchioBartolomeoColleoni",
  "QID_wikidata": "",
  "entry_type": "artwork",
  "title": "Statue équestre du Colleone ; Bartolomeo Colleoni de Bergame",
  "creator": [
    {
      "xml_id": "AlessandroLeopardi",
      "role": "fondeur"
    }
  ],
  "dateCreated": {
    "startYear": 1483,
    "endYear": 1488,
    "text": "1483-1488"
  },
  "materialsAndTechniques": "sculpture en bronze",
  "location": {
    "type": "holding_institution",
    "institution": {
      "name": "",
      "place": "",
      "inventory_number": "",
      "url": ""
    }
  },
  "related_works": [],
  "bibliography": [],
  "illustrations": [],
  "description": "",
  "commentary": "",
  "history": [
    {
      "date": "2026-01-14T11:44:39.685875",
      "type": "created",
      "author": "Carla"
    }
  ],
  "complete_entry": false
}

=== ANR-ArTerm/index_oeuvres/data/entry_artwork/VenezianoManne.json
{
  "id": "VenezianoManne",
  "QID_wikidata": "",
  "title": "La Manne",
  "creator": [
    {
      "xml_id": "AgostinoVeneziano",
      "role": "graveur"
    }
  ],
  "entry_type": "artwork",
  "materialsAndTechniques": "",
  "dateCreated": {
    "startYear": null,
    "endYear": null,
    "text": ""
  },
  "location": {
    "type": "multiple_locations"
  },
  "related_works": [],
  "bibliography": [
    {
      "zotero_key": "straussIllustratedBartsch261978",
      "location": "n° 8 (10)"
    }
  ],
  "illustrations": [],
  "description": "",
  "commentary": "",
  "history": [
    {
      "date": "2026-03-06T14:48:18.470629",
      "type": "created",
      "author": "Pierre"
    }
  ],
  "complete_entry": false
}

=== ANR-ArTerm/index_oeuvres/data/entry_artwork/RaphaelNocesPsycheFarnesina.json
{
  "id": "RaphaelNocesPsycheFarnesina",
  "QID_wikidata": "",
  "entry_type": "artwork",
  "title": "Noces de Psyché",
  "creator": [
    {
      "xml_id": "Raphael",
      "role": "peintre"
    }
  ],
  "dateCreated": {
    "startYear": 1518,
    "endYear": 1518,
    "text": "1518"
  },
  "location": {
    "type": "holding_institution",
    "institution": {
      "name": "Villa Farnesina",
      "place": "",
      "inventory_number": "",
      "url": ""
    }
  },
  "related_works": [],
  "bibliography": [
    {
      "zotero_key": "dusslerRaphaelCriticalCatalogue1971",
      "location": "p. 97"
    }
  ],
  "illustrations": [
    {
      "id": 0,
      "url": "https://upload.wikimedia.org/wikipedia/commons/d/d4/Raffaello%2C_banchetto_nuziale_02.jpg",
      "copyright": "Wikimedia Commons, https://commons.wikimedia.org/wiki/File:Raffaello,_banchetto_nuziale_02.jpg",
      "caption": "",
      "storage": "online"
    }
  ],
  "description": "",
  "commentary": "",
  "history": [
    {
      "date": "2026-02-04T15:45:41.167889",
      "type": "created",
      "author": "Pierre"
    },
    {
      "date": "2026-02-04T15:54:19.144166",
      "type": "modified",
      "author": "Pierre"
    },
    {
      "date": "2026-02-04T16:40:30.459663",
      "type": "modified",
      "author": "Pierre"
    }
  ],
  "materialsAndTechniques": "fresque",
  "contained_by_ensemble": {
    "link_type": "appartient à l'ensemble",
    "xml_id_work": "LoggiaPsyche"
  },
  "complete_entry": false
}

=== ANR-ArTerm/index_oeuvres/data/entry_artwork/RavennaBatailleCoutelas.json
{
  "id": "RavennaBatailleCoutelas",
  "QID_wikidata": "",
  "entry_type": "artwork",
  "title": "Bataille au coutelas",
  "creator": [
    {
      "xml_id": "MarcoDente",
      "role": "graveur"
    },
    {
      "xml_id": "GiulioRomano",
      "role": "auteur du modèle (?)"
    }
  ],
  "dateCreated": {
    "startYear": null,
    "endYear": null,
    "text": ""
  },
  "location": {
    "type": "multiple_locations"
  },
  "related_works": [],
  "bibliography": [
    {
      "zotero_key": "straussIllustratedBartsch261978",
      "location": "n° 211 (171)"
    }
  ],
  "illustrations": [
    {
      "id": 0,
      "url": "https://collectionapi.metmuseum.org/api/collection/v1/iiif/345601/771378/main-image",
      "storage": "online",
      "copyright": "New York, Metropolitan Museum of Arts, inv. 17.50.19-124 (https://www.metmuseum.org/art/collection/search/345601)",
      "caption": ""
    }
  ],
  "description": "",
  "commentary": "",
  "history": [
    {
      "date": "2026-03-06T17:34:47.649936",
      "type": "created",
      "author": "Pierre"
    }
  ],
  "materialsAndTechniques": "burin",
  "contained_by_ensemble": {},
  "complete_entry": false
}
