=== ANR-ArTerm/index_oeuvres/schema/artwork.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "http://example.com/artwork.schema.json",
  "title": "Artwork Entry",
  "type": "object",
  "required": [
    "id",
    "entry_type",
    "title"
  ],
  "properties": {
    "id": {
      "type": "string"
    },
    "QID_wikidata": {
      "type": "string"
    },
    "entry_type": {
      "type": "string",
      "enum": ["artwork"]
    },
    "title": {
      "type": "string"
    },
    "creator": {
      "type": "array",
      "items": {
        "type": "object",
        "required": ["xml_id", "role"],
        "properties": {
          "xml_id": {
            "type": "string"
          },
          "role": {
            "type": "string"
          }
        },
        "additionalProperties": false
      }
    },
    "dateCreated": {
      "type": "object",
      "properties": {
        "startYear": {
          "type": ["integer", "null"],
          "minimum": -9999,
          "maximum": 9999
        },
        "endYear": {
          "type": ["integer", "null"],
          "minimum": -9999,
          "maximum": 9999
        },
        "text": {
          "type": "string"
        }
      },
      "additionalProperties": false
    },
    "materialsAndTechniques": {
      "type": "string"
    },
    "location": {
        "oneOf": [
            {
            "type": "object",
            "required": ["type", "institution"],
            "properties": {
                "type": {
                "type": "string",
                "enum": ["holding_institution"]
                },
                "institution": {
                "type": "object",
                "required": ["name"],
                "properties": {
                    "name": { "type": "string" },
                    "place": { "type": "string" },
                    "inventory_number": { "type": "string" },
                    "url": { "type": "string", "format": "uri" }
                },
                "additionalProperties": false
                }
            },
            "additionalProperties": false
            },
            {
            "type": "object",
            "required": ["type", "place"],
            "properties": {
                "type": {
                "type": "string",
                "enum": ["place"]
                },
                "place": {
                "type": "object",
                "properties": {
                    "city": { "type": "string" },
                    "country": { "type": "string" },
                    "coordinates": {
                    "type": "object",
                    "properties": {
                        "latitude": { "type": "number" },
                        "longitude": { "type": "number" }
                    },
                    "required": ["latitude", "longitude"],
                    "additionalProperties": false
                    }
                },
                "additionalProperties": false
                }
            },
            "additionalProperties": false
            },
            {
            "type": "object",
            "required": ["type"],
            "properties": {
                "type": {
                "type": "string",
                "enum": ["unlocated", "multiple_locations"]
                }
            },
            "additionalProperties": false
            }
        ]
    },
    "related_works": {
      "type": "array",
      "items": {
        "type": "object",
        "required": ["link_type", "xml_id_work"],
        "properties": {
          "link_type": {
            "type": "string"
          },
          "xml_id_work": {
            "type": "string"
          }
        },
        "additionalProperties": false
      }
    },
    "contained_by_ensemble": {
      "type": "object",
      "properties": {
        "link_type": {
          "type": "string"
        },
        "xml_id_work": {
          "type": "string"
        }
      },
      "additionalProperties": false
    },
    "bibliography": {
      "type": "array",
      "items": {
        "type": "object",
        "required": ["zotero_key"],
        "properties": {
          "zotero_key": {
            "type": "string"
          },
          "location": {
            "type": "string"
          }
        },
        "additionalProperties": false
      }
    },
    "illustrations": {
      "type": "array",
      "items": {
        "type": "object",
        "required": ["id", "url"],
        "properties": {
          "id": {
            "type": "integer"
          },
          "url": {
            "type": "string",
            "format": "uri"
          },
          "copyright": {
            "type": "string"
          },
          "caption": {
            "type": "string"
          },
          "storage": {
            "type": "string"
          }
        },
        "additionalProperties": false
      }
    },
    "description": {
      "type": "string"
    },
    "commentary": {
      "type": "string"
    },
    "history": {
      "type": "array",
      "items": {
        "type": "object",
        "required": ["date", "type", "author"],
        "properties": {
          "date": {
            "type": "string",
            "format": "date-time"
          },
          "type": {
            "type": "string",
            "enum": ["created", "modified"]
          },
          "author": {
            "type": "string"
          }
        },
        "additionalProperties": false
      },
      "minItems": 1
    },
    "complete_entry": {
      "type":"boolean"
    }
  },
  "additionalProperties": false
}

=== ANR-ArTerm/index_oeuvres/data/entry_artwork/ParmesanPierreJeanMalades.json
{
  "id": "ParmesanPierreJeanMalades",
  "QID_wikidata": "",
  "title": "Saint Pierre et saint Jean guérissent les malades à la porte du temple",
  "creator": [
    {
      "xml_id": "Parmigianino",
      "role": "graveur"
    }
  ],
  "entry_type": "artwork",
  "materialsAndTechniques": "",
  "dateCreated": {
    "startYear": null,
    "endYear": null,
    "text": ""
  },
  "location": {
    "type": "multiple_locations"
  },
  "related_works": [],
  "bibliography": [
    {
      "zotero_key": "straussIllustratedBartsch321979",
      "location": "n° 7 (9)"
    }
  ],
  "illustrations": [],
  "description": "",
  "commentary": "",
  "history": [
    {
      "date": "2026-03-06T14:48:18.473002",
      "type": "created",
      "author": "Pierre"
    }
  ],
  "complete_entry": false
}

=== ANR-ArTerm/index_oeuvres/data/entry_artwork/VenezianoPsyche.json
{
  "id": "VenezianoPsyche",
  "QID_wikidata": "",
  "title": "Histoire de Psyché (3 planches)",
  "creator": [
    {
      "xml_id": "AgostinoVeneziano",
      "role": "graveur"
    }
  ],
  "entry_type": "artwork",
  "materialsAndTechniques": "burin",
  "dateCreated": {
    "startYear": null,
    "endYear": null,
    "text": ""
  },
  "location": {
    "type": "multiple_locations"
  },
  "related_works": [],
  "bibliography": [
    {
      "zotero_key": "straussIllustratedBartsch261978",
      "location": "n° 236 (190)"
    }
  ],
  "illustrations": [],
  "description": "",
  "commentary": "",
  "history": [
    {
      "date": "2026-03-06T14:48:18.471497",
      "type": "created",
      "author": "Pierre"
    }
  ],
  "complete_entry": false
}

=== ANR-ArTerm/index_oeuvres/data/entry_artwork/BolswertRubensVueMalines.json
{
  "id": "BolswertRubensVueMalines",
  "QID_wikidata": "",
  "entry_type": "artwork",
  "title": "Vue de Malines (Suite de six grands paysages)",
  "creator": [
    {
      "xml_id": "SchelteBolswert",
      "role": "graveur"
    },
    {
      "xml_id": "PeterPaulRubens",
      "role": "auteur du modèle"
    }
  ],
  "dateCreated": {
    "startYear": null,
    "endYear": null,
    "text": ""
  },
  "location": {
    "type": "multiple_locations"
  },
  "related_works": [],
  "bibliography": [],
  "illustrations": [
    {
      "id": 0,
      "url": "https://apicollections.parismusees.paris.fr/sites/default/files/styles/4k/collections/atoms/images/PPA/lpdp_80895-16.jpg?itok=5mr6lUd5",
      "storage": "online",
      "copyright": "Petit Palais, Musées des Beaux-arts de la ville de Paris, inv. GDUT8312 (https://www.parismuseescollections.paris.fr/fr/petit-palais/oeuvres/vue-de-malines-d-apres-rubens-dutuit-264-p-249)",
      "caption": ""
    }
  ],
  "description": "",
  "commentary": "",
  "history": [
    {
      "date": "2026-03-09T14:56:52.991267",
      "type": "created",
      "author": "Pierre"
    }
  ],
  "materialsAndTechniques": "burin",
  "contained_by_ensemble": {},
  "complete_entry": false
}

=== ANR-ArTerm/index_oeuvres/data/entry_artwork/DominiquinPortementCroixGetty.json
{
  "id": "DominiquinPortementCroixGetty",
  "QID_wikidata": "https://www.wikidata.org/wiki/Q20180050",
  "entry_type": "artwork",
  "title": "Le Portement de la Croix po",
  "creator": [
    {
      "xml_id": "Dominiquin",
      "role": "peintre"
    }
  ],
  "dateCreated": {
    "startYear": 1610,
    "endYear": 1610,
    "text": "1610"
  },
  "location": {
    "type": "holding_institution",
    "institution": {
      "name": "Getty Center",
      "place": "Los Angeles",
      "inventory_number": " 83.PC.373",
      "url": "https://www.getty.edu/art/collection/object/103RFK"
    }
  },
  "related_works": [],
  "bibliography": [],
  "illustrations": [
    {
      "id": 0,
      "url": "https://upload.wikimedia.org/wikipedia/commons/8/8f/Domenichino_%28Domenico_Zampieri%29_%28Italian%29_-_The_Way_to_Calvary_-_Google_Art_Project.jpg?utm_source=commons.wikimedia.org&utm_campaign=index&utm_content=original",
      "copyright": "Wikimedia Commons, Domaine public, https://commons.wikimedia.org/wiki/File:Domenichino_(Domenico_Zampieri)_-_The_Way_to_Calvary_-_83.PC.373_-_J._Paul_Getty_Museum.jpg?uselang=fr",
      "caption": "",
      "storage": "online"
    }
  ],
  "description": "",
  "commentary": "",
  "history": [
    {
      "date": "2026-05-05T17:38:03.356972",
      "type": "created",
      "author": "Carla"
    },
    {
      "date": "2026-05-05T18:20:00.062023",
      "type": "modified",
      "author": "Carla"
    }
  ],
  "materialsAndTechniques": "Huile sur cuivre",
  "contained_by_ensemble": {},
  "complete_entry": false
}

=== ANR-ArTerm/index_oeuvres/data/entry_artwork/RaphaelMadonnaCardellino.json
{
  "id": "RaphaelMadonnaCardellino",
  "QID_wikidata": "https://www.wikidata.org/wiki/Q2344505",
  "entry_type": "artwork",
  "title": "La Vierge au chardonneret",
  "creator": [
    {
      "xml_id": "Raphael",
      "role": "peintre"
    }
  ],
  "dateCreated": {
    "startYear": null,
    "endYear": null,
    "text": ""
  },
  "materialsAndTechniques": "",
  "location": {
    "type": "holding_institution",
    "institution": {
      "name": "",
      "place": "",
      "inventory_number": "",
      "url": ""
    }
  },
  "related_works": [],
  "bibliography": [
    {
      "zotero_key": "meyerzurcapellenRaphaelCriticalCatalogue2001",
      "location": "n° 27"
    }
  ],
  "illustrations": [],
  "description": "",
  "commentary": "",
  "history": [
    {
      "date": "2026-01-15T16:40:40.173298",
      "type": "created",
      "author": "Pierre"
    }
  ],
  "complete_entry": false
}

=== ANR-ArTerm/index_oeuvres/corbeille/RaphaelTapisseriesSixtine.json
{
  "id": "RaphaelTapisseriesSixtine",
  "QID_wikidata": "https://www.wikidata.org/wiki/Q76844726",
  "entry_type": "artwork",
  "title": "Tenture des Actes des Apôtres",
  "creator": [
    {
      "xml_id": "Raphael",
      "role": "auteur du modèle"
    }
  ],
  "dateCreated": {
    "startYear": 1521,
    "endYear": 1521,
    "text": "1521"
  },
  "location": {
    "type": "holding_institution",
    "institution": {
      "name": "Vatican, Chapelle Sixtine",
      "place": "Rome",
      "inventory_number": "",
      "url": ""
    }
  },
  "related_works": [
    {
      "link_type": "œuvre associée",
      "xml_id_work": "RaphaelCartonsTapisseriesApotres"
    }
  ],
  "bibliography": [],
  "illustrations": [
    {
      "id": 0,
      "url": "https://upload.wikimedia.org/wikipedia/commons/c/c6/Sistina_con_arazzi.jpg",
      "storage": "online",
      "copyright": "Domaine public, https://commons.wikimedia.org/wiki/File:Sistina_con_arazzi.jpg",
      "caption": ""
    }
  ],
  "description": "",
  "commentary": "",
  "history": [
    {
      "date": "2026-02-04T13:04:13.159693",
      "type": "created",
      "author": "Carla"
    },
    {
      "date": "2026-02-04T13:10:50.366799",
      "type": "modified",
      "author": "Carla"
    },
    {
      "date": "2026-02-04T14:51:27.081812",
      "type": "modified",
      "author": "Carla"
    }
  ],
  "materialsAndTechniques": "Tapisserie",
  "contained_by_ensemble": {
    "link_type": "appartient à l'ensemble",
    "xml_id_work": "ChapelleSixtine"
  }
}

=== ANR-ArTerm/index_oeuvres/data/entry_artwork/Allegoriecyclevie.json
{
  "id": "Allegoriecyclevie",
  "QID_wikidata": "",
  "entry_type": "artwork",
  "title": "Allégorie du cycle de la vie",
  "creator": [
    {
      "xml_id": "CosimoBartoli",
      "role": "auteur du modèle"
    }
  ],
  "dateCreated": {
    "startYear": null,
    "endYear": null,
    "text": "Au milieu de XVIe siècle"
  },
  "location": {
    "type": "unlocated"
  },
  "related_works": [],
  "bibliography": [],
  "illustrations": [],
  "description": "Cycle conçu par Bartoli dans un loggia qui représente en huit scènes une allégorie du cycle de la vie.",
  "commentary": "",
  "history": [
    {
      "date": "2026-05-05T12:42:02.307809",
      "type": "created",
      "author": "Elisa"
    }
  ],
  "materialsAndTechniques": "fresque",
  "contained_by_ensemble": {},
  "complete_entry": false
}

=== ANR-ArTerm/index_oeuvres/data/entry_artwork/CaraglioPlutonProserpine.json
{
  "id": "CaraglioPlutonProserpine",
  "QID_wikidata": "",
  "title": "Pluton et Proserpine",
  "creator": [
    {
      "xml_id": "GiovanniJacopoCaraglio",
      "role": "graveur"
    }
  ],
  "entry_type": "artwork",
  "materialsAndTechniques": "",
  "dateCreated": {
    "startYear": null,
    "endYear": null,
    "text": ""
  },
  "location": {
    "type": "multiple_locations"
  },
  "related_works": [],
  "bibliography": [
    {
      "zotero_key": "straussIllustratedBartsch281985",
      "location": "n° 22 (76)"
    }
  ],
  "illustrations": [],
  "description": "",
  "commentary": "A voir si on le considère comme une série avec des images",
  "history": [
    {
      "date": "2026-03-06T14:48:18.473189",
      "type": "created",
      "author": "Pierre"
    }
  ],
  "complete_entry": false
}
